/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as DatasetsImport } from "./routes/datasets";
import { Route as ReplayRunsImport } from "./routes/replay-runs";
import { Route as PromotionsImport } from "./routes/promotions";
import { Route as RedTeamImport } from "./routes/red-team";
import { Route as AuditLogImport } from "./routes/audit-log";
import { Route as TracesIndexImport } from "./routes/traces.index";
import { Route as TracesTraceIdImport } from "./routes/traces.$traceId";

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const DatasetsRoute = DatasetsImport.update({
  id: "/datasets",
  path: "/datasets",
  getParentRoute: () => rootRoute,
} as any);

const ReplayRunsRoute = ReplayRunsImport.update({
  id: "/replay-runs",
  path: "/replay-runs",
  getParentRoute: () => rootRoute,
} as any);

const PromotionsRoute = PromotionsImport.update({
  id: "/promotions",
  path: "/promotions",
  getParentRoute: () => rootRoute,
} as any);

const RedTeamRoute = RedTeamImport.update({
  id: "/red-team",
  path: "/red-team",
  getParentRoute: () => rootRoute,
} as any);

const AuditLogRoute = AuditLogImport.update({
  id: "/audit-log",
  path: "/audit-log",
  getParentRoute: () => rootRoute,
} as any);

const TracesIndexRoute = TracesIndexImport.update({
  id: "/traces/",
  path: "/traces/",
  getParentRoute: () => rootRoute,
} as any);

const TracesTraceIdRoute = TracesTraceIdImport.update({
  id: "/traces/$traceId",
  path: "/traces/$traceId",
  getParentRoute: () => rootRoute,
} as any);

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DatasetsRoute,
  ReplayRunsRoute,
  PromotionsRoute,
  RedTeamRoute,
  AuditLogRoute,
  TracesIndexRoute,
  TracesTraceIdRoute,
]);
