#!/bin/sh
# gatelane container entrypoint.
#
# Responsibilities:
#   1. Generate a fresh GATELANE_CAPTURE_TOKEN if none is provided (>= 32 chars).
#   2. Materialize a per-container env file the supervisor children can read.
#   3. Hand off to supervisord which runs the worker + dashboard.
set -eu

ENV_FILE="${GATELANE_HOME}/.env"

if [ -z "${GATELANE_CAPTURE_TOKEN:-}" ]; then
  # Prefer /dev/urandom; fall back to openssl, then date+random.
  if command -v openssl >/dev/null 2>&1; then
    GATELANE_CAPTURE_TOKEN="$(openssl rand -hex 32)"
  else
    GATELANE_CAPTURE_TOKEN="$(head -c 32 /dev/urandom | base64 | tr -d '\n=')"
  fi
  export GATELANE_CAPTURE_TOKEN
fi

# Persist the token across restarts in /data so dev mounts survive.
{
  echo "# generated by gatelane entrypoint on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "GATELANE_CAPTURE_TOKEN=${GATELANE_CAPTURE_TOKEN}"
  echo "GATELANE_JUDGE_PROVIDER=${GATELANE_JUDGE_PROVIDER:-openai}"
  echo "GATELANE_JUDGE_MODEL=${GATELANE_JUDGE_MODEL:-gpt-4o}"
} > "${ENV_FILE}"

echo "gatelane: worker on :${GATELANE_WORKER_PORT}, dashboard on :${GATELANE_DASHBOARD_PORT}"
echo "gatelane: token persisted to ${ENV_FILE}"

exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf