import { createFileRoute } from "@tanstack/react-router";
import { DataTable } from "../components/DataTable";
import { StatusBadge } from "../components/StatusBadge";

interface AttackResultRow {
  vectorId: string;
  targetId: string;
  success: boolean;
  payload: string;
  patchRecommendation: string;
  latencyMs: number;
  [key: string]: unknown;
}

export const Route = createFileRoute("/red-team" as any)({
  component: RedTeamPage,
});

function RedTeamPage() {
  const mockResults: AttackResultRow[] = [];

  return (
    <>
      <h1 style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>Red Team Reports</h1>
      <p style={{ color: "#6b7280", marginBottom: 24, fontSize: 14 }}>
        Attack reports generated by <code>pnpm gatelane redteam</code>.
        Upload a <code>report.json</code> or connect the API to view results here.
      </p>
      <DataTable
        columns={[
          { key: "vectorId", label: "Attack Vector" },
          { key: "targetId", label: "Target" },
          { key: "success", label: "Result", render: (r) => (
            <StatusBadge status={r.success ? "failed" : "completed"} />
          )},
          { key: "payload", label: "Payload", render: (r) => (
            <code style={{ fontSize: 12 }}>{String(r.payload).slice(0, 80)}...</code>
          )},
          { key: "latencyMs", label: "Latency" },
          { key: "patchRecommendation", label: "Patch" },
        ]}
        rows={mockResults}
        emptyMessage="No attack reports loaded. Run: pnpm gatelane redteam --report report.json"
      />
    </>
  );
}
