import { useState, useCallback } from "react";
import { Layout } from "../components/Layout";
import { DataTable } from "../components/DataTable";
import { StatusBadge } from "../components/StatusBadge";

interface Vulnerability {
  item_id: string;
  category: string;
  mapped_asi: string;
  score: number;
  outcome: string;
  reasoning: string;
  attack: string;
  response: string;
  [key: string]: unknown;
}

interface CandidateSummary {
  candidate_ref: string;
  total: number;
  survived: number;
  failed: number;
  survival_rate: number;
  vulnerabilities: Vulnerability[];
  [key: string]: unknown;
}

interface AsiGap {
  asi: string;
  failed: number;
  total: number;
  fail_rate: number;
  [key: string]: unknown;
}

interface ScanReport {
  mode: string;
  generated_at: string;
  dataset_content_hash: string;
  candidates: CandidateSummary[];
  by_asi: AsiGap[];
}

export function RedTeamPage() {
  const [report, setReport] = useState<ScanReport | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleFileUpload = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setError(null);

    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const parsed = JSON.parse(ev.target?.result as string) as ScanReport;
        if (!parsed.candidates || !Array.isArray(parsed.candidates)) {
          setError("Invalid report format: missing 'candidates' array");
          return;
        }
        setReport(parsed);
      } catch {
        setError("Failed to parse JSON file");
      }
    };
    reader.readAsText(file);
  }, []);

  return (
    <Layout current="#red-team">
      <h1 style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>Red Team Reports</h1>
      <p style={{ color: "#6b7280", marginBottom: 16, fontSize: 14 }}>
        Upload a scan report generated by <code>gatelane scan --report report.json</code>.
      </p>

      <div style={{ marginBottom: 24 }}>
        <label style={{
          display: "inline-block", padding: "8px 20px", fontSize: 14,
          background: "#2563eb", color: "#fff", borderRadius: 8, cursor: "pointer",
        }}>
          Upload report.json
          <input type="file" accept=".json" onChange={handleFileUpload} style={{ display: "none" }} />
        </label>
        {report && (
          <span style={{ marginLeft: 12, fontSize: 13, color: "#6b7280" }}>
            Loaded: {report.candidates.length} candidate(s), generated {report.generated_at}
          </span>
        )}
      </div>

      {error && <p style={{ color: "#dc2626", marginBottom: 16 }}>{error}</p>}

      {!report && (
        <div style={{ padding: 40, textAlign: "center", color: "#9ca3af" }}>
          No attack reports loaded. Run: <code>gatelane scan --report report.json</code>
        </div>
      )}

      {report && (
        <>
          <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 12 }}>Candidate Survival Rates</h2>
          <DataTable
            columns={[
              { key: "candidate_ref", label: "Candidate" },
              { key: "survived", label: "Survived" },
              { key: "failed", label: "Failed" },
              { key: "total", label: "Total" },
              { key: "survival_rate", label: "Survival Rate", render: (r) => {
                const rate = Number(r.survival_rate);
                return (
                  <span style={{ fontWeight: 600, color: rate >= 0.8 ? "#166534" : rate >= 0.5 ? "#854d0e" : "#991b1b" }}>
                    {(rate * 100).toFixed(0)}%
                  </span>
                );
              }},
            ]}
            rows={report.candidates}
          />

          {report.candidates.map((candidate) => (
            candidate.vulnerabilities.length > 0 && (
              <div key={candidate.candidate_ref} style={{ marginTop: 24 }}>
                <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 12 }}>
                  Vulnerabilities: {candidate.candidate_ref} ({candidate.vulnerabilities.length})
                </h2>
                <DataTable
                  columns={[
                    { key: "item_id", label: "ID" },
                    { key: "category", label: "Category" },
                    { key: "mapped_asi", label: "ASI" },
                    { key: "outcome", label: "Outcome", render: (r) => (
                      <StatusBadge status={String(r.outcome) === "fail" ? "failed" : String(r.outcome)} />
                    )},
                    { key: "score", label: "Score", render: (r) => Number(r.score).toFixed(2) },
                    { key: "attack", label: "Attack", render: (r) => (
                      <code style={{ fontSize: 12 }}>{String(r.attack).slice(0, 80)}...</code>
                    )},
                    { key: "response", label: "Response", render: (r) => (
                      <code style={{ fontSize: 12 }}>{String(r.response).slice(0, 80)}...</code>
                    )},
                  ]}
                  rows={candidate.vulnerabilities}
                />
              </div>
            )
          ))}

          {report.by_asi.length > 0 && (
            <div style={{ marginTop: 24 }}>
              <h2 style={{ fontSize: 18, fontWeight: 600, marginBottom: 12 }}>OWASP ASI Gaps</h2>
              <DataTable
                columns={[
                  { key: "asi", label: "ASI" },
                  { key: "failed", label: "Failed" },
                  { key: "total", label: "Total" },
                  { key: "fail_rate", label: "Fail Rate", render: (r) => {
                    const rate = Number(r.fail_rate);
                    return (
                      <span style={{ fontWeight: 600, color: rate >= 0.5 ? "#991b1b" : rate >= 0.2 ? "#854d0e" : "#166534" }}>
                        {(rate * 100).toFixed(0)}%
                      </span>
                    );
                  }},
                ]}
                rows={report.by_asi}
              />
            </div>
          )}
        </>
      )}
    </Layout>
  );
}
