/**
 * @lanefoundry/gatelane-ci-adapter — parse gatelane gate output for CI/CD.
 *
 * Reads the JSON report produced by `gatelane eval --report` or `gatelane run --report`,
 * extracts the promotion decision, and maps it to GitHub Actions outputs / exit codes.
 */

export type GateDecision = 'promote' | 'rollback' | 'hold_for_review';

export type ParsedGateOutput = {
  decision: GateDecision;
  winner?: string;
  reason: string;
  report_id: string;
  signature: string;
};

/**
 * Parse the JSON report from `gatelane eval` or `gatelane run`.
 * Accepts the full report JSON string.
 */
export function parseGateOutput(jsonString: string): ParsedGateOutput {
  const raw = JSON.parse(jsonString) as Record<string, unknown>;

  const decision = raw.decision as Record<string, unknown> | undefined;
  if (!decision || typeof decision !== 'object') {
    throw new Error('report missing "decision" field');
  }

  const action = String(decision.action ?? 'rollback');
  if (action !== 'promote' && action !== 'rollback' && action !== 'hold_for_review') {
    throw new Error(`unexpected decision action: "${action}"`);
  }

  return {
    decision: action,
    winner: 'winner' in decision ? String(decision.winner) : undefined,
    reason: String(decision.reason ?? ''),
    report_id: String(raw.report_id ?? raw.gate_run_id ?? ''),
    signature: String(raw.signature ?? ''),
  };
}

/**
 * Map parsed gate output to GitHub Actions output variables.
 */
export function toGitHubOutput(parsed: ParsedGateOutput): Record<string, string> {
  return {
    GATELANE_DECISION: parsed.decision,
    GATELANE_WINNER: parsed.winner ?? '',
    GATELANE_REASON: parsed.reason,
    GATELANE_REPORT_ID: parsed.report_id,
  };
}

/**
 * Map decision to process exit code.
 * promote / hold_for_review = 0 (CI passes), rollback = 1 (CI fails).
 */
export function exitCodeForDecision(decision: GateDecision): number {
  return decision === 'rollback' ? 1 : 0;
}

/**
 * Format a markdown summary for GitHub Actions step summary.
 */
export function formatGitHubSummary(parsed: ParsedGateOutput): string {
  const icon = parsed.decision === 'promote' ? ':white_check_mark:'
    : parsed.decision === 'hold_for_review' ? ':warning:'
    : ':x:';

  const lines = [
    `## ${icon} gatelane gate: ${parsed.decision.toUpperCase()}`,
    '',
  ];

  if (parsed.winner) {
    lines.push(`**Winner:** \`${parsed.winner}\``);
  }
  lines.push(`**Reason:** ${parsed.reason}`);
  lines.push(`**Report ID:** \`${parsed.report_id}\``);

  if (parsed.signature) {
    lines.push(`**Signature:** \`${parsed.signature.slice(0, 16)}...\``);
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [gatelane](https://github.com/lanefoundry/gatelane)*');

  return lines.join('\n');
}
